### ISSUE TITLE
Please add light theme

### ISSUE THREAD

**Issue by ptah-alexs** [matteo-convertino/otpmanager-nextcloud#1]
Subj

**Comment by matteo-convertino** [comment]
The theme is taken directly from nextcloud, if you have nextcloud in light mode the extension will be too

**Comment by ptah-alexs** [comment]
I use system default theme, it's light, but otp manager used dark. When I'm set light theme in NC, then app actually is set  light theme.

**Comment by matteo-convertino** [comment]
What version of nextcloud are you using?

**Comment by ptah-alexs** [comment]
26.0.1

**Comment by matteo-convertino** [comment]
This should be solved with version [v0.1.9](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.1.9).
Feel free to re-open if you still encounter the problem.
