### ISSUE TITLE
Feature Request: Ability to share OTPs

### ISSUE THREAD

**Issue by Saijin-Naib** [matteo-convertino/otpmanager-nextcloud#13]
It would be very helpful it we were able to "share" OTPs within our NextCloud organization, especially if we can set Share limits like to a certain group, user, a period of time, etc.

Use case:  
Shared management of accounts, like social media, requiring 2FA for extra security

The "main" user isn't always available to provide the 2FA response through other channels, so being able to "share" certain accounts within the NextCloud instance is incredibly helpful, just as we can currently share passwords this way.

**Comment by matteo-convertino** [comment]
This will certainly be one of the next features to be developed :smile:.

**Comment by matteo-convertino** [comment]
With a bit of waiting, this feature arrived with the latest release. Let me know if you have any feedback.
