### ISSUE TITLE
Phone App: Lock the app when not in use

### ISSUE THREAD

**Issue by JoshuaPettus** [matteo-convertino/otpmanager-nextcloud#15]
One important feature that is missing from the phone apps, or at least the android version, that similar apps usually have, is any mechanism that uses the phones security to lock the app when it is not open, or at the very least a pin that can be set in the app.  Granted the phone should be locked anyway, but there is a chance if someone were to grab the phone while it was unlocked they could get into the app.

**Comment by JoshuaPettus** [comment]
Oh it's right with an option for configurable timer.   That works!  Not sure what password on every sync means.  That doesn't seem to lock the app, but I may be using it wrong.

**Comment by matteo-convertino** [comment]
`every sync` means that you will be asked for your password at every synchronization in which you need to decrypt the accounts (for example when you add one).

**Comment by JoshuaPettus** [comment]
Ah, I see.  So the ask for password is completely different then what I was hoping.   I'd reopen this here but I just realized this should go in the ios/android app repo.  Apologies for that,  Ill make it over there.  Thank you!
