### ISSUE TITLE
Nextcloud 28?

### ISSUE THREAD

**Issue by JoshuaPettus** [matteo-convertino/otpmanager-nextcloud#19]
Has anyone had a chance to see if this is working with NC28 even if unofficially for the time being?

**Comment by BeRo1985** [comment]
I wonder the same thing. I sincerely hope that OTP Manager is not dead.

**Comment by matteo-convertino** [comment]
Don't worry, I always check all issues and updates :eyes:. OTP Manager is not dead. Since I'm a student this is always a period full of studies and exams, then I'm also working on [this project](https://github.com/matteo-convertino/asyncher) so my free time doesn't exist.
I have set myself the goal that in these Christmas "holidays" I will return to this project and close as many issues as possible :grimacing:.

**Comment by JoshuaPettus** [comment]
Oh naturally,  this is a crazy time of year for many people.  I fully expect people don't get around to updating stuff till January at the earliest, providing there are no large hurdles to overcome.    I was asking if anyone had forced it to run on 28 and if there were any issues.

**Comment by JoshuaPettus** [comment]
Has anyone tried this app yet in 28?  or are we all still on 27? :)

**Comment by BeRo1985** [comment]
I'm on NC28 and I've tried it. With NC28 it doesn't work, even if I'm force-enabling it as non-tested app for NC28. 

![image](https://github.com/matteo-convertino/otpmanager-nextcloud/assets/428863/16dd0688-021a-4880-8001-9d46a42dad52)

**Comment by BeRo1985** [comment]
Ok after a new attempt, it works:

![image](https://github.com/matteo-convertino/otpmanager-nextcloud/assets/428863/2ba01912-c65d-4bb4-8183-b0049fbdd481)

**Comment by JoshuaPettus** [comment]
That's good maybe all he will have to do is change max NC version number.   *fingers crossed*

**Comment by JoshuaPettus** [comment]
I just took the plunge to NC28 myself and forced it to run.  I can confirm.  It seems to work just fine.  Integration and sync with the android phone app still works.  I can still create new OTP accounts and the menus all seem to work.

**Comment by matteo-convertino** [comment]
I just published the [version](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.3.3) that should support Nextcloud 28. Let me know if there are any problems.
