### ISSUE TITLE
Backup accounts and codes

### ISSUE THREAD

**Issue by gmOjjFj9Ezm2** [matteo-convertino/otpmanager-nextcloud#2]
How do you or when will the feature to backup/export your OTP accounts and secrets be available?

**Comment by matteo-convertino** [comment]
Exporting and importing accounts is a nice feature to implement, thanks for the suggestion. When I will be able to publish it I can't tell you, hopefully as soon as possible.

**Comment by gmOjjFj9Ezm2** [comment]
Any update on this feature?

**Comment by matteo-convertino** [comment]
For what type of use are you thinking/needing to export all accounts? For example, in what format should we export them?

**Comment by gmOjjFj9Ezm2** [comment]
mainly as a personal backup of the data in case of server failure, I would think JSON is easiest, but there should also be an import in the browser app and mobile app to all for JSON, I believe now the mobile app only allows Google Auth import format. My current ask was prompted by my setting up a new Nextcloud server and not wanting to restoring anything, just do a true new install and for all other apps like Contacts, Calendar, Bookmarks, etc., they have export functions so I can easily export from old and import on new server as I desire.

**Comment by matteo-convertino** [comment]
This feature should be added with the [v0.3.0](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.3.0) release. Feel free to re-open the issue if any problem appears.
