### ISSUE TITLE
FreeOTP Plus to Nextcloud OTP Manager conversion script

### ISSUE THREAD

**Issue by ghost** [matteo-convertino/otpmanager-nextcloud#20]
I created an simple python script to convert the [Free OTP](https://freeotp.github.io) json file to otpmanager json format:

https://github.com/betabrandao/utils/blob/main/filecopys/freeotp2nextcloudotp.py

Simple use: `python3 freeotp2nextcloudotp.py freeotp_exported.json >> otpmanager.json`

:)

**Comment by matteo-convertino** [comment]
I'm really grateful that you developed it. As soon as possible I will mention it in the readme and, why not, also in the mobile and web app.

It would be really cool to have more scripts like this that allow the user to easily import all of his accounts from other software as well.

**Comment by matteo-convertino** [comment]
I was trying to test the script but I don't understand one thing: the FreeOTP app when I export the backup file is an `xml` while the script expects a `json`. What am I doing wrong?

**Comment by matteo-convertino** [comment]
I'm closing only because it doesn't make sense to have it as an open "issue". However, I am waiting for the response since I would like to add this script to OTP Manager.

**Comment by ghost** [comment]
> I was trying to test the script but I don't understand one thing: the FreeOTP app when I export the backup file is an `xml` while the script expects a `json`. What am I doing wrong?

Ohh I'm sorry. This script run in [FreeOTP+](https://github.com/helloworld1/FreeOTPPlus) , fork of Redhat FreeOTP app.

**Comment by matteo-convertino** [comment]
![screenshot](https://github.com/user-attachments/assets/5748af1d-0ba2-465e-b971-76d6515c2af6)
With a little delay I wanted to let you know that I added this in the modal to import accounts, so if anyone needs it they can use your script. Thanks again :heart:.

**Comment by zyll71** [comment]
> I was trying to test the script but I don't understand one thing: the FreeOTP app when I export the backup file is an `xml` while the script expects a `json`. What am I doing wrong?

I just ran into the same issue. Has this been solved? If yes, please, how?

**Comment by matteo-convertino** [comment]
Simply Free OTP and Free OTP Plus are two different apps. Most likely you have Free OTP, while the script works with Free OTP Plus.

**Comment by Digitwellsolutions** [comment]
@matteo-convertino The link in the first post does not work anymore. Is there another way to import Free OTP plus JSON files?

**Comment by matteo-convertino** [comment]
https://web.archive.org/ is always a safe bet.

I’ve reposted the script with my profile, here’s the link: https://gist.github.com/matteo-convertino/39ed696ff5b462f27b7b7070f7a4753a
