### ISSUE TITLE
Password reset, forgot?

### ISSUE THREAD

**Issue by tomspatz** [matteo-convertino/otpmanager-nextcloud#28]
While iam testing, i did not document the password i set for one user.
Is it possible to reset this anyway?

**Comment by matteo-convertino** [comment]
At this time it is not possible to recover your password. From what I understand you were only using it for testing, so what I can tell you to do is to clean the two tables directly from the db(`oc_otpmanager_accounts`, `oc_otpmanager_settings`), so as to start from scratch.

**Comment by tomspatz** [comment]
No idea how to manage this, mean to get access to the DB. Sounds easy but my NC runs completely in a docker.

**Comment by matteo-convertino** [comment]
You should access the Nextcloud container shell and then it depends on the type of db you have... for example in my case I execute the command  `sqlite3 data/nextcloud.db` and then `delete from oc_otpmanager_accounts;` and `delete from oc_otpmanager_settings;`. In this way I cleaned the two tables.

**Comment by tomspatz** [comment]
Ok fo rme it works this way: (Nextcloud, Maria DB with swag in docker)
First ssh to the device and log in.
`docker exec -it nextcloddb bash`  --  nextclouddb is the namy of MY Nextcloud DB
`mysql -u root -p` --  root is the DB root then enter password for the DB
`show databases;`  --  shows u all DB on this device
`use nextclouddatabase name;`  --  u found above with show
`drop table oc_otpmanager_accounts;`
`drop table oc_otpmanager_settings;`
Both are gone afterthis. I restarted the DB and the NC containers, then i install the otp manager app from the frontend of NC again.
All looks good but if i try to access the App only the darker screen appears ant the donut is turning around.
Guess this was not the way it should happen. 
"delete" should be better i think after read tons of internet searches :(
Still get a look at my database and unfortunately both tables miss in the DB.
So both DB Tables are not created after reinstall the App ??

**Comment by matteo-convertino** [comment]
From what I remember, Nextcloud stores information regarding the migrations of installed apps in another of its tables. I'm not sure, but I think that by deleting the entries from the `oc_migrations` table you should be able to force the tables to be created.
Try running this command: `delete from oc_migrations where app="otpmanager";`

_(I'm closing the issue only because it no longer concerns the "forgot password", but don't hesitate to write here if you still have the problem)_

**Comment by tomspatz** [comment]
This works perfecktly, many thanks.
Guess it is much better to read the man pages for the first and not to serch on web for similar things ;)
I would write a feature request as a "notepad" for u.
