### ISSUE TITLE
[Bug] Page selector hidden when switching to higher records per page

### ISSUE THREAD

**Issue by meichthys** [matteo-convertino/otpmanager-nextcloud#3]
Steps to Reproduce:
- Add alot of entries
- Make sure "Records per Page" is set to 10
- Navigate to last page of records
- Switch to 30 records per page
- Notice that no records are displayed and page selector is hidden (although still clickable)

On another note, if it's not too resource intensive, why not just allow all records to show on the first page?

**Comment by matteo-convertino** [comment]
This bug should be fixed with the [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.2.0). If the problem persists feel free to reopen the issue.
