### ISSUE TITLE
OTP Manager v0.4.0 just loads to a spinning wheel

### ISSUE THREAD

**Issue by s3rverro0m** [matteo-convertino/otpmanager-nextcloud#40]
I installed OTP Manager v0.4.0 today and when I go to the app, the homepage turns dark and has a continuous spinning wheel. I've deleted the app, reinstalled, restarted Nextcloud, Postgres and Redis just in case which didn't resolve the issue. I then looked at the Nextcloud.log which showed that oc_otpmanager_settings does not exist. 

patcher","type":"->","args":[["OCA\\OtpManager\\Controller\\PasswordController"],"get"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":
"OC\\AppFramework\\App","type":"::","args":["OCA\\OtpManager\\Controller\\PasswordController","get",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["otpmanager.password.ge
t"]]},{"file":"/var/www/html/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/otpmanager/password"]},{"file":"/var/www/html/inde
x.php","line":39,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":130}}},"message"
:"An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"oc_otpmanager_settings\" does not exist\nLINE 1: INSERT INTO \"oc_otpmanage
r_settings\" (\"show_codes\", \"dark_mo...\n                    ^","exception":{},"CustomMessage":"An exception occurred while executing a query: SQLSTATE[42P01]: Undefined table:
 7 ERROR:  relation \"oc_otpmanager_settings\" does not exist\nLINE 1: INSERT INTO \"oc_otpmanager_settings\" (\"show_codes\", \"dark_mo...\n                    ^"}}

I'm assuming when the app installed, this table wasn't created? Should I try manually creating the table?

TIA!

**Comment by matteo-convertino** [comment]
It's strange that the table wasn't automatically created during the first installation. I would suggest you try uninstalling the extension again and especially deleting the migrations with this command `delete from oc_migrations where app="otpmanager";`. This should make the installation cleaner.

**Comment by s3rverro0m** [comment]
It looks like that worked! I had to use single quotes and not double quotes. Thanks so much!
