### ISSUE TITLE
no connection with iOS possible after updating to version 0.5.3

### ISSUE THREAD

**Issue by odesee** [matteo-convertino/otpmanager-nextcloud#44]
After updating to version 0.5.3, the iOS app does not connect to the Nextcloud server. When trying to set up the account again, the error message "Server not available" appears. After downgrading to version 4.0, everything seems to work as usual again - please help!

**Comment by matteo-convertino** [comment]
Version 0.5.3 only allows synchronization to app mobile with [version 1.5.1](https://github.com/matteo-convertino/otpmanager-app/releases/tag/v1.5.1). I'm sorry but at the moment there is no release for iOS yet.

**Comment by odesee** [comment]
When will version 1.5.1. be released for iOS?

**Comment by matteo-convertino** [comment]
Good question... I'm not the one who manages the publication on the app store, so I couldn't tell you.

**Comment by odesee** [comment]
ok, then I have to wait with the upgrade to version 0.5.3
