### ISSUE TITLE
Documentation for forgotten password workflow

### ISSUE THREAD

**Issue by ClaskoTheKnight** [matteo-convertino/otpmanager-nextcloud#47]
I forgot my OTP unlocking password, and I couldn't find any easily available documentation about how to reset the particular user's OTP credentials, even if it wouldn't allow them to access their old OTP passwords.

**Comment by matteo-convertino** [comment]
In truth, at this time there is no way to "recover" your password if you don't remember it. The only way at the moment is to reset the app (losing all accounts), you can do it this way: 
```
DROP TABLE oc_otpmanager_accounts;
DROP TABLE oc_otpmanager_settings;
DROP TABLE oc_otpmanager_shared;
```
```
DELETE FROM oc_migrations WHERE app="otpmanager";
```
```
DELETE FROM oc_appconfig WHERE appid="otpmanager";
```

Then you can reinstall the app from scratch.

**Comment by ghost** [comment]
Well, i deleted the issued user from database, without losing all accounts:

`delete from oc_otpmanager_accounts where user_id  = 'NEXTCLOUD_USER_ID';`
`delete from oc_otpmanager_settings where user_id  = 'NEXTCLOUD_USER_ID';`

**Comment by gudini-nsk** [comment]
if you update just:
 `delete from oc_otpmanager_settings where user_id  = 'NEXTCLOUD_USER_ID'; `
user can recreate password.
