### ISSUE TITLE
Nextcloud 29 support?

### ISSUE THREAD

**Issue by r0gueone** [matteo-convertino/otpmanager-nextcloud#48]
I just stumbled across this app for Nextcloud and it works brilliantly in my 28.x environment.  However, since 29 is out, I'm curious if this is still active and will it be made available for 29?

**Comment by matteo-convertino** [comment]
Yes, I should check if everything works for the new version. Unfortunately now I don't think I can do it but it is planned.

**Comment by JoshuaPettus** [comment]
29 has been working fine for me. I haven't had any issues.

**Comment by Lin2mars** [comment]
@JoshuaPettus, 
Did you click on "Authorize non-tested application"-like button ?

**Comment by JoshuaPettus** [comment]
> @JoshuaPettus, Did you click on "Authorize non-tested application"-like button ?

Of course

**Comment by philipgunstone** [comment]
I too can confirm that I have OTP manager enabled adn working in NC29.0.3 without any issue
pg

**Comment by matteo-convertino** [comment]
Guys (with quite a delay) the app now supports version 29 of Nextcloud. New release: [v0.5.4](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.5.4).
