### ISSUE TITLE
[Feature Request] Allow clicking code to copy to clipboard

### ISSUE THREAD

**Issue by meichthys** [matteo-convertino/otpmanager-nextcloud#5]
Currently in the web view, if you click directly on a code, it opens the right sidebar to view details.
It would be nice to be able to click directly on the code itself to copy to the clipboard like is possible in most OTP mobile apps.

![image](https://github.com/matteo-convertino/otpmanager-app/assets/10717998/30fba958-005d-4092-befe-29e15e177597)

**Comment by matteo-convertino** [comment]
The feature to copy clicking directly on the code has been implemented with the [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.2.0). If problems appear feel free to reopen the issue.
