### ISSUE TITLE
[Feature Request] Show all codes

### ISSUE THREAD

**Issue by meichthys** [matteo-convertino/otpmanager-nextcloud#6]
Currently the web view paginates the codes. There is an option to show up to 30 codes per page, but it would be nice to be able to see all codes on the same page regardless of the number.

A quick easy fix would be to just increase the number of allowed records per page:
image

Perhaps a scale like the following would be good?
10
25
50
100
All <This would be nice but probably not necessary

**Comment by matteo-convertino** [comment]
The option to view all accounts has been implemented with the [release](https://github.com/matteo-convertino/otpmanager-nextcloud/releases/tag/v0.2.0). If problems appear feel free to reopen the issue.
